language: node_js
node_js:
  - "0.10"

before_script:
  - npm install -g jspm
  - npm install -g divshot-cli
  - jspm config endpoints.github.auth $JSPM_AUTH
  - jspm install
script:
  - divshot push development -t $DIVSHOT_KEY
